app/code/community/Doofinder/Feed/Block/Settings/Buttons/Generate.php
app/code/community/Doofinder/Feed/Helper/Data.php
app/code/community/Doofinder/Feed/Model/Observers/Schedule.php
app/code/community/Doofinder/Feed/etc/config.xml

- Changed functionality of "Generate Feed" to generate feed using cron
- Changed scheduling logic to schedule for current day if selected start time is not missed
- Fixed cron expression for logs clearing job

Cron improvements & fixes 

---

app/code/community/Doofinder/Feed/Block/Settings/Panel/File.php
app/code/community/Doofinder/Feed/etc/system.xml

- Fixed the block with a file in the feed admin panel
- Added a summary of already generated feeds to the feed admin panel in global scope

Feed panel improvements

---

app/code/community/Doofinder/Feed/Block/Settings/Panel/File.php

Added full url to file to feed panel in global scope

Added full url to file to feed panel in global scope

---

app/code/community/Doofinder/Feed/controllers/FeedController.php

- Added options preparation from store config in index action of doofinder controller

Update old feed controller

---

app/code/community/Doofinder/Feed/Block/Settings/Buttons/Generate.php
app/code/community/Doofinder/Feed/etc/system.xml

- Fixed missing generate button in default context
- Fixed missing current storeview in generate button url

Generate button fixes

---

app/code/community/Doofinder/Feed/controllers/FeedController.php
app/code/community/Doofinder/Feed/etc/system.xml

- Added "feed_exists" property to feed config action
- Renamed "Start Time" label to "Feed generation start time"
- Switched field "Start Delay" order with "Start Time"

Minor changes to feed config action and UI section

---

app/code/community/Doofinder/Feed/Helper/Search.php
app/code/community/Doofinder/Feed/Model/CatalogSearch/Resource/Fulltext.php
app/code/community/Doofinder/Feed/etc/config.xml
app/code/community/Doofinder/Feed/etc/system.xml
lib/Doofinder/Api.php

- Provide simple internal search configuration
- Add doofinder search in place of internal Magento search
- Provide simple API query for retrieving search results

Add simple internal search functionality

---

app/code/community/Doofinder/Feed/Model/Generator.php
app/code/community/Doofinder/Feed/Model/Map/Product/Abstract.php

It should convert all remaning html entities into decoded utf-8 character.

Fix html entities in xml.

---

app/code/community/Doofinder/Feed/Model/CatalogSearch/Resource/Fulltext.php

Reverts doofinder/doofinder-magento#61

Revert "Add filtering out of non-existing products in catalog search results"

---

app/code/community/Doofinder/Feed/Model/CatalogSearch/Resource/Fulltext.php

by filling in _foundData property.

Fix compatibility with Magento 1.9.3.0+

---

app/code/community/Doofinder/Feed/Helper/Data.php

Hotfix: replace $storeCode with $code in _processXmlName method

---

app/code/community/Doofinder/Feed/Model/Observers/Feed.php

This should allow to save products even if error occurs.

Add handling atomic update errors during product search

---

app/code/community/Doofinder/Feed/Block/Settings/Panel/Crondescription.php
app/code/community/Doofinder/Feed/Block/Settings/Panel/Description.php
app/code/community/Doofinder/Feed/Block/Settings/Panel/Hashdescription.php
app/code/community/Doofinder/Feed/Block/Settings/Panel/Layerdescription.php

Change-Id: Ib19a0ae7fd0a1622aea6c359bdaf3fdf0d7b318c

Hotfix: Add syntax fixes for long strings in php5.5

---

app/code/community/Doofinder/Feed/Block/Settings/Panel/File.php

refs #57715
Change-Id: I6c48152eb06964df0f69849ed2c29aab4a59bf35

Hotfix: Fix cron alert condition in feed status panel

---

app/code/community/Doofinder/Feed/Model/CatalogSearch/Resource/Fulltext.php

Change-Id: I9a9f752f2809959d26d7af7d131adbf2930dae94

Hotfix: Fix missing parameter error in fulltext search resource

---

app/code/community/Doofinder/Feed/Model/System/Config/Source/Feed/Pricetaxmode.php

refs #58343
Change-Id: If54339e0fd7ec7997b49497ab0d4ac0c63b3565c

Bugfix: Remove global call to __() function

---

app/code/community/Doofinder/Feed/Model/Generator.php

refs #58900
Change-Id: Id2a5384cc6c614362b3d069a3d6c2b1ad6fa305c

Bugfix: Add checking if category is included in menu for all ancestors

---

app/code/community/Doofinder/Feed/Model/System/Config/Backend/Map/Additional.php
app/code/community/Doofinder/Feed/etc/system.xml

refs #60491
Change-Id: I0643e2e51ac729c96d56bb2a28dbb641e26080aa

Enforce lowercase and no whitespaces in "field" in additional attributes

---

app/code/community/Doofinder/Feed/Helper/Data.php
app/code/community/Doofinder/Feed/Model/Map/Product/Abstract.php
app/code/community/Doofinder/Feed/etc/config.xml

refs #61939
Change-Id: I04e2b7b23dbe0ae91bb3cb007295a864e7b3534a

Add Tier Price directive

---

app/code/community/Doofinder/Feed/Model/Map/Product/Abstract.php

refs #62303
Change-Id: I82385390c66febc25c32e0e66affabdd0c1e546e

Use a double slash but only for SKU

---

app/code/community/Doofinder/Feed/Model/Map/Product/Bundle.php

refs #63848
Change-Id: I9b3cf035d6028b87917b1095d4297cff94a45836

Fix getting price for bundle product
